# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: >
    (?x)^(
        bsp/aws_configs/|
        bsp/platform/|
        bsp/freertos-config/|
        bsp/default_credentials/|
        bsp/tf_m_targets/|
        examples/speech/include/dsp|
        examples/speech/source/dsp|
        lib/
    )
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: ['--maxkb=2500']
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.4
    hooks:
    -   id: clang-format -i
        args:
        - "-style=file:developer-tools/.clang-format"
-   repo: https://github.com/jorisroovers/gitlint
    rev:  v0.17.0
    hooks:
    -   id: gitlint
        args:
        - "--config developer-tools/.gitlint"
-   repo: https://git.gitlab.arm.com/iot/open-iot-sdk/tools/developer-tools.git
    rev: 25a1de6f78bade94a8893512b973fe1ddfed0a58
    hooks:
    -   id: cppcheck
    -   id: banned-api
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
